// <auto-generated />
using APIInt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIInt.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20251030171705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIInt.Models.emp", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eid"));

                    b.Property<string>("eemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("epass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("eid");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
